version: '3'

services:

  prometheus:
    image: prom/prometheus:v2.22.1
    restart: on-failure
    command: --config.file=/etc/prometheus/config/prometheus.yml
    environment:
      GATLING_PROMETHEUS_HOST: gatling
      GATLING_PROMETHEUS_PORT: 9102
    volumes:
      - ./config/prometheus/:/etc/prometheus/config/
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:7.3.1
    restart: on-failure
    environment:
      GF_LOG_LEVEL: warn
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ORG_ROLE: "viewer"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
    volumes:
      - ./config/grafana/datasource.yml:/etc/grafana/provisioning/datasources/prometheus.yml
      - ./config/grafana/dashboard-providers.yml:/etc/grafana/provisioning/dashboards/dashboard-providers.yml
      - ./config/grafana/dashboards/:/var/lib/grafana/dashboards/
    ports:
      - 3000:3000
    depends_on:
      - prometheus

  gatling:
    image: gatling
    build:
      context: ./config/gatling
      args:
        GATLING_VERSION: "3.4.1"
    ports:
      - 9102:9102