{
 "title": "Gatling",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "aggregation", "label": "Aggregation", "query": "5s,10s,30s,1m,5m,30m,1h" },
   { "name": "gatlingWriteInterval", "query": "5" },
   {
    "name": "GatlingTransaction",
    "label": "Gatling Operation",
    "query": "label_values(groupRequestInfo_sum, group)"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total TPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(groupRequestInfo_sum[25s]))"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(groupRequestInfo_sum[25s])/rate(groupRequestInfo_count[25s]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(groupRequestInfo_bucket[25s])) by (le))",
     "legendFormat": "90pct"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(groupRequestInfo_bucket[25s])) by (le))",
     "legendFormat": "95pct"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(groupRequestInfo_bucket[25s])) by (le))",
     "legendFormat": "99pct"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "total_started_users", "legendFormat": "Thread count" }
   ]
  },
  {
   "title": "Aggregate Report",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(\nmax_over_time(groupRequestInfo_count[${__range_s}s]) \n- min_over_time(groupRequestInfo_count[${__range_s}s])\n) by (group)",
     "legendFormat": "requests"
    },
    {
     "expr": "avg(\n(max_over_time(groupRequestInfo_sum[${__range_s}s]) - min_over_time(groupRequestInfo_sum[${__range_s}s]))\n/ (max_over_time(groupRequestInfo_count[${__range_s}s]) - min_over_time(groupRequestInfo_count[${__range_s}s]))\n) by (group)",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(groupRequestInfo_bucket[${__range_s}s])) by (le))",
     "legendFormat": "90pct"
    },
    {
     "expr": "sum(\nmax_over_time(groupRequestInfo_count{oK=\"KO\"}[${__range_s}s])\n- min_over_time(groupRequestInfo_count{oK=\"KO\"}[${__range_s}s])\n) by (group)\n/ sum(\nmax_over_time(groupRequestInfo_count[${__range_s}s])\n- min_over_time(groupRequestInfo_count[${__range_s}s])\n) by (group)",
     "legendFormat": "errors"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Error Rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(\nmax_over_time(groupRequestInfo_count{oK=\"KO\"}[${__range_s}s])\n- min_over_time(groupRequestInfo_count{oK=\"KO\"}[${__range_s}s])\n)\n/ sum(\nmax_over_time(groupRequestInfo_count[${__range_s}s])\n- min_over_time(groupRequestInfo_count[${__range_s}s])\n)"
    }
   ]
  },
  {
   "title": "Errors per Transaction",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 30 },
   "targets": [
    {
     "expr": "sum(\nmax_over_time(groupRequestInfo_count{oK=\"KO\"}[${__range_s}s])\n- min_over_time(groupRequestInfo_count{oK=\"KO\"}[${__range_s}s])\n) by (group)\n",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Error Info",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 30 },
   "targets": [
    {
     "expr": "sum(\nmax_over_time(requests_latency_secondsHistogram_count{oK=\"KO\"}[${__range_s}s])\n- min_over_time(requests_latency_secondsHistogram_count{oK=\"KO\"}[${__range_s}s])\n) by (error, responseCode)"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(requests_latency_secondsHistogram_count{oK=~\"KO\"}[1m])) by (responseCode)",
     "legendFormat": "Response Code = {{responseCode}}"
    }
   ]
  },
  {
   "title": "Gatling Operation -  $GatlingTransaction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "repeat": "GatlingTransaction"
  },
  {
   "title": "TPS - $GatlingTransaction",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(requests_latency_secondsHistogram_count{group=\"$GatlingTransaction\"}[25s])) by (oK)"
    }
   ]
  },
  {
   "title": "Response Time - $GatlingTransaction",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(groupRequestInfo_sum{group=\"$GatlingTransaction\"}[25s])/rate(groupRequestInfo_count{group=\"$GatlingTransaction\"}[25s]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(groupRequestInfo_bucket{group=\"$GatlingTransaction\"}[25s])) by (le))",
     "legendFormat": "90pct"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(groupRequestInfo_bucket{group=\"$GatlingTransaction\"}[25s])) by (le))",
     "legendFormat": "95pct"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(groupRequestInfo_bucket{group=\"$GatlingTransaction\"}[25s])) by (le))",
     "legendFormat": "99pct"
    }
   ]
  },
  {
   "title": "Transaction Info",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "sum(\nmax_over_time(requests_latency_secondsHistogram_count{group=\"$GatlingTransaction\", responseCode!=\"0\"}[${__range_s}s]) \n- min_over_time(requests_latency_secondsHistogram_count{group=\"$GatlingTransaction\", responseCode!=\"0\"}[${__range_s}s])\n) by (metric, responseCode)"
    }
   ]
  },
  {
   "title": "Transaction Errors Info",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "sum(\nmax_over_time(requests_latency_secondsHistogram_count{group=\"$GatlingTransaction\", responseCode!=\"0\", error!=\"\"}[${__range_s}s]) \n- min_over_time(requests_latency_secondsHistogram_count{group=\"$GatlingTransaction\", responseCode!=\"0\", error!=\"\"}[${__range_s}s])\n) by (metric, error, responseCode)"
    }
   ]
  },
  {
   "title": "% Errors By Requests",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(\nmax_over_time(requests_latency_secondsHistogram_count{group=\"$GatlingTransaction\", oK=\"KO\"}[${__range_s}s])\n- min_over_time(requests_latency_secondsHistogram_count{group=\"$GatlingTransaction\", oK=\"KO\"}[${__range_s}s])\n) by (metric)\n/ sum(\nmax_over_time(requests_latency_secondsHistogram_count{group=\"$GatlingTransaction\"}[${__range_s}s])\n- min_over_time(requests_latency_secondsHistogram_count{group=\"$GatlingTransaction\"}[${__range_s}s])\n) by (metric)",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  {
   "title": "Gatling Operation -  $GatlingTransaction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 }
  },
  {
   "title": "TPS - $GatlingTransaction",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(requests_latency_secondsHistogram_count{group=\"$GatlingTransaction\"}[25s])) by (oK)"
    }
   ]
  },
  {
   "title": "Response Time - $GatlingTransaction",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(groupRequestInfo_sum{group=\"$GatlingTransaction\"}[25s])/rate(groupRequestInfo_count{group=\"$GatlingTransaction\"}[25s]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(groupRequestInfo_bucket{group=\"$GatlingTransaction\"}[25s])) by (le))",
     "legendFormat": "90pct"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(groupRequestInfo_bucket{group=\"$GatlingTransaction\"}[25s])) by (le))",
     "legendFormat": "95pct"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(groupRequestInfo_bucket{group=\"$GatlingTransaction\"}[25s])) by (le))",
     "legendFormat": "99pct"
    }
   ]
  },
  {
   "title": "Transaction Info",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "sum(\nmax_over_time(requests_latency_secondsHistogram_count{group=\"$GatlingTransaction\", responseCode!=\"0\"}[${__range_s}s]) \n- min_over_time(requests_latency_secondsHistogram_count{group=\"$GatlingTransaction\", responseCode!=\"0\"}[${__range_s}s])\n) by (metric, responseCode)"
    }
   ]
  },
  {
   "title": "Transaction Errors Info",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 75 },
   "targets": [
    {
     "expr": "sum(\nmax_over_time(requests_latency_secondsHistogram_count{group=\"$GatlingTransaction\", responseCode!=\"0\", error!=\"\"}[${__range_s}s]) \n- min_over_time(requests_latency_secondsHistogram_count{group=\"$GatlingTransaction\", responseCode!=\"0\", error!=\"\"}[${__range_s}s])\n) by (metric, error, responseCode)"
    }
   ]
  },
  {
   "title": "% Errors By Requests",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(\nmax_over_time(requests_latency_secondsHistogram_count{group=\"$GatlingTransaction\", oK=\"KO\"}[${__range_s}s])\n- min_over_time(requests_latency_secondsHistogram_count{group=\"$GatlingTransaction\", oK=\"KO\"}[${__range_s}s])\n) by (metric)\n/ sum(\nmax_over_time(requests_latency_secondsHistogram_count{group=\"$GatlingTransaction\"}[${__range_s}s])\n- min_over_time(requests_latency_secondsHistogram_count{group=\"$GatlingTransaction\"}[${__range_s}s])\n) by (metric)",
     "legendFormat": "{{metric}}"
    }
   ]
  }
 ]
}